module.exports = [{
    "name": "Bitcoin",
    "symbol": "BTC",
    "thumb": "https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png"
}, {
    "name": "Ethereum",
    "symbol": "ETH",
    "thumb": "https://assets.coingecko.com/coins/images/279/thumb/ethereum.png"
}, {
    "name": "Binance Coin",
    "symbol": "BNB",
    "thumb": "https://assets.coingecko.com/coins/images/825/thumb/binance-coin-logo.png"
}, {
    "name": "Dogecoin",
    "symbol": "DOGE",
    "thumb": "https://assets.coingecko.com/coins/images/5/thumb/dogecoin.png"
}, {
    "name": "XRP",
    "symbol": "XRP",
    "thumb": "https://assets.coingecko.com/coins/images/44/thumb/xrp-symbol-white-128.png"
}, {
    "name": "Tether",
    "symbol": "USDT",
    "thumb": "https://assets.coingecko.com/coins/images/325/thumb/Tether-logo.png"
}, {
    "name": "Cardano",
    "symbol": "ADA",
    "thumb": "https://assets.coingecko.com/coins/images/975/thumb/cardano.png"
}, {
    "name": "Polkadot",
    "symbol": "DOT",
    "thumb": "https://assets.coingecko.com/coins/images/12171/thumb/aJGBjJFU_400x400.jpg"
}, {
    "name": "Bitcoin Cash",
    "symbol": "BCH",
    "thumb": "https://assets.coingecko.com/coins/images/780/thumb/bitcoin-cash-circle.png"
}, {
    "name": "Litecoin",
    "symbol": "LTC",
    "thumb": "https://assets.coingecko.com/coins/images/2/thumb/litecoin.png"
}, {
    "name": "Uniswap",
    "symbol": "UNI",
    "thumb": "https://assets.coingecko.com/coins/images/12504/thumb/uniswap-uni.png"
}, {
    "name": "Chainlink",
    "symbol": "LINK",
    "thumb": "https://assets.coingecko.com/coins/images/877/thumb/chainlink-new-logo.png"
}, {
    "name": "USD Coin",
    "symbol": "USDC",
    "thumb": "https://assets.coingecko.com/coins/images/6319/thumb/USD_Coin_icon.png"
}, {
    "name": "Stellar",
    "symbol": "XLM",
    "thumb": "https://assets.coingecko.com/coins/images/100/thumb/Stellar_symbol_black_RGB.png"
}, {
    "name": "VeChain",
    "symbol": "VET",
    "thumb": "https://assets.coingecko.com/coins/images/1167/thumb/VeChain-Logo-768x725.png"
}, {
    "name": "Solana",
    "symbol": "SOL",
    "thumb": "https://assets.coingecko.com/coins/images/4128/thumb/coinmarketcap-solana-200.png"
}, {
    "name": "Ethereum Classic",
    "symbol": "ETC",
    "thumb": "https://assets.coingecko.com/coins/images/453/thumb/ethereum-classic-logo.png"
}, {
    "name": "Theta Network",
    "symbol": "THETA",
    "thumb": "https://assets.coingecko.com/coins/images/2538/thumb/theta-token-logo.png"
}, {
    "name": "Filecoin",
    "symbol": "FIL",
    "thumb": "https://assets.coingecko.com/coins/images/12817/thumb/filecoin.png"
}, {
    "name": "TRON",
    "symbol": "TRX",
    "thumb": "https://assets.coingecko.com/coins/images/1094/thumb/tron-logo.png"
}, {
    "name": "OKB",
    "symbol": "OKB",
    "thumb": "https://assets.coingecko.com/coins/images/4463/thumb/okb_token.png"
}, {
    "name": "Wrapped Bitcoin",
    "symbol": "WBTC",
    "thumb": "https://assets.coingecko.com/coins/images/7598/thumb/wrapped_bitcoin_wbtc.png"
}, {
    "name": "EOS",
    "symbol": "EOS",
    "thumb": "https://assets.coingecko.com/coins/images/738/thumb/eos-eos-logo.png"
}, {
    "name": "NEO",
    "symbol": "NEO",
    "thumb": "https://assets.coingecko.com/coins/images/480/thumb/NEO_512_512.png"
}, {
    "name": "Bitcoin SV",
    "symbol": "BSV",
    "thumb": "https://assets.coingecko.com/coins/images/6799/thumb/BSV.png"
}, {
    "name": "Binance USD",
    "symbol": "BUSD",
    "thumb": "https://assets.coingecko.com/coins/images/9576/thumb/BUSD.png"
}, {
    "name": "Monero",
    "symbol": "XMR",
    "thumb": "https://assets.coingecko.com/coins/images/69/thumb/monero_logo.png"
}, {
    "name": "Terra",
    "symbol": "LUNA",
    "thumb": "https://assets.coingecko.com/coins/images/8284/thumb/luna1557227471663.png"
}, {
    "name": "PancakeSwap",
    "symbol": "CAKE",
    "thumb": "https://assets.coingecko.com/coins/images/12632/thumb/IMG_0440.PNG"
}, {
    "name": "Klaytn",
    "symbol": "KLAY",
    "thumb": "https://assets.coingecko.com/coins/images/9672/thumb/CjbT82vP_400x400.jpg"
}, {
    "name": "Aave",
    "symbol": "AAVE",
    "thumb": "https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png"
}, {
    "name": "Cosmos",
    "symbol": "ATOM",
    "thumb": "https://assets.coingecko.com/coins/images/1481/thumb/cosmos_hub.png"
}, {
    "name": "IOTA",
    "symbol": "MIOTA",
    "thumb": "https://assets.coingecko.com/coins/images/692/thumb/IOTA_Swirl.png"
}, {
    "name": "Tezos",
    "symbol": "XTZ",
    "thumb": "https://assets.coingecko.com/coins/images/976/thumb/Tezos-logo.png"
}, {
    "name": "cETH",
    "symbol": "CETH",
    "thumb": "https://assets.coingecko.com/coins/images/10643/thumb/ceth2.JPG"
}, {
    "name": "FTX Token",
    "symbol": "FTT",
    "thumb": "https://assets.coingecko.com/coins/images/9026/thumb/F.png"
}, {
    "name": "Maker",
    "symbol": "MKR",
    "thumb": "https://assets.coingecko.com/coins/images/1364/thumb/Mark_Maker.png"
}, {
    "name": "Polygon",
    "symbol": "MATIC",
    "thumb": "https://assets.coingecko.com/coins/images/4713/thumb/matic___polygon.jpg"
}, {
    "name": "BitTorrent",
    "symbol": "BTT",
    "thumb": "https://assets.coingecko.com/coins/images/7595/thumb/BTT_Token_Graphic.png"
}, {
    "name": "Crypto.com Coin",
    "symbol": "CRO",
    "thumb": "https://assets.coingecko.com/coins/images/7310/thumb/cypto.png"
}, {
    "name": "Avalanche",
    "symbol": "AVAX",
    "thumb": "https://assets.coingecko.com/coins/images/12559/thumb/coin-round-red.png"
}, {
    "name": "Huobi Token",
    "symbol": "HT",
    "thumb": "https://assets.coingecko.com/coins/images/2822/thumb/huobi-token-logo.png"
}, {
    "name": "cUSDC",
    "symbol": "CUSDC",
    "thumb": "https://assets.coingecko.com/coins/images/9442/thumb/Compound_USDC.png"
}, {
    "name": "Algorand",
    "symbol": "ALGO",
    "thumb": "https://assets.coingecko.com/coins/images/4380/thumb/download.png"
}, {
    "name": "THORChain",
    "symbol": "RUNE",
    "thumb": "https://assets.coingecko.com/coins/images/6595/thumb/RUNE.png"
}, {
    "name": "Dai",
    "symbol": "DAI",
    "thumb": "https://assets.coingecko.com/coins/images/9956/thumb/dai-multi-collateral-mcd.png"
}, {
    "name": "Compound",
    "symbol": "COMP",
    "thumb": "https://assets.coingecko.com/coins/images/10775/thumb/COMP.png"
}, {
    "name": "cDAI",
    "symbol": "CDAI",
    "thumb": "https://assets.coingecko.com/coins/images/9281/thumb/cDAI.png"
}, {
    "name": "Dash",
    "symbol": "DASH",
    "thumb": "https://assets.coingecko.com/coins/images/19/thumb/dash-logo.png"
}, {
    "name": "Kusama",
    "symbol": "KSM",
    "thumb": "https://assets.coingecko.com/coins/images/9568/thumb/m4zRhP5e_400x400.jpg"
}, {
    "name": "Waves",
    "symbol": "WAVES",
    "thumb": "https://assets.coingecko.com/coins/images/425/thumb/waves.png"
}, {
    "name": "NEM",
    "symbol": "XEM",
    "thumb": "https://assets.coingecko.com/coins/images/242/thumb/NEM_Logo_256x256.png"
}, {
    "name": "Elrond",
    "symbol": "EGLD",
    "thumb": "https://assets.coingecko.com/coins/images/12335/thumb/Elrond.png"
}, {
    "name": "Zcash",
    "symbol": "ZEC",
    "thumb": "https://assets.coingecko.com/coins/images/486/thumb/circle-zcash-color.png"
}, {
    "name": "LEO Token",
    "symbol": "LEO",
    "thumb": "https://assets.coingecko.com/coins/images/8418/thumb/leo-token.png"
}, {
    "name": "Chiliz",
    "symbol": "CHZ",
    "thumb": "https://assets.coingecko.com/coins/images/8834/thumb/Chiliz.png"
}, {
    "name": "Synthetix Network Token",
    "symbol": "SNX",
    "thumb": "https://assets.coingecko.com/coins/images/3406/thumb/SNX.png"
}, {
    "name": "Holo",
    "symbol": "HOT",
    "thumb": "https://assets.coingecko.com/coins/images/3348/thumb/Holologo_Profile.png"
}, {
    "name": "Bitcoin Gold",
    "symbol": "BTG",
    "thumb": "https://assets.coingecko.com/coins/images/1043/thumb/bitcoin-gold-logo.png"
}, {
    "name": "Zilliqa",
    "symbol": "ZIL",
    "thumb": "https://assets.coingecko.com/coins/images/2687/thumb/Zilliqa-logo.png"
}, {
    "name": "Decred",
    "symbol": "DCR",
    "thumb": "https://assets.coingecko.com/coins/images/329/thumb/decred.png"
}, {
    "name": "Hedera Hashgraph",
    "symbol": "HBAR",
    "thumb": "https://assets.coingecko.com/coins/images/3688/thumb/mqTDGK7Q.png"
}, {
    "name": "Celsius Network",
    "symbol": "CEL",
    "thumb": "https://assets.coingecko.com/coins/images/3263/thumb/CEL_logo.png"
}, {
    "name": "Sushi",
    "symbol": "SUSHI",
    "thumb": "https://assets.coingecko.com/coins/images/12271/thumb/512x512_Logo_no_chop.png"
}, {
    "name": "Enjin Coin",
    "symbol": "ENJ",
    "thumb": "https://assets.coingecko.com/coins/images/1102/thumb/enjin-coin-logo.png"
}, {
    "name": "Stacks",
    "symbol": "STX",
    "thumb": "https://assets.coingecko.com/coins/images/2069/thumb/Stacks_logo_full.png"
}, {
    "name": "Amp",
    "symbol": "AMP",
    "thumb": "https://assets.coingecko.com/coins/images/12409/thumb/amp-200x200.png"
}, {
    "name": "NEXO",
    "symbol": "NEXO",
    "thumb": "https://assets.coingecko.com/coins/images/3695/thumb/nexo.png"
}, {
    "name": "Basic Attention Token",
    "symbol": "BAT",
    "thumb": "https://assets.coingecko.com/coins/images/677/thumb/basic-attention-token.png"
}, {
    "name": "DigiByte",
    "symbol": "DGB",
    "thumb": "https://assets.coingecko.com/coins/images/63/thumb/digibyte.png"
}, {
    "name": "TerraUSD",
    "symbol": "UST",
    "thumb": "https://assets.coingecko.com/coins/images/12681/thumb/UST.png"
}, {
    "name": "Fantom",
    "symbol": "FTM",
    "thumb": "https://assets.coingecko.com/coins/images/4001/thumb/Fantom.png"
}, {
    "name": "yearn.finance",
    "symbol": "YFI",
    "thumb": "https://assets.coingecko.com/coins/images/11849/thumb/yfi-192x192.png"
}, {
    "name": "Siacoin",
    "symbol": "SC",
    "thumb": "https://assets.coingecko.com/coins/images/289/thumb/siacoin.png"
}, {
    "name": "Near",
    "symbol": "NEAR",
    "thumb": "https://assets.coingecko.com/coins/images/10365/thumb/near_icon.png"
}, {
    "name": "The Graph",
    "symbol": "GRT",
    "thumb": "https://assets.coingecko.com/coins/images/13397/thumb/Graph_Token.png"
}, {
    "name": "Qtum",
    "symbol": "QTUM",
    "thumb": "https://assets.coingecko.com/coins/images/684/thumb/qtum.png"
}, {
    "name": "Decentraland",
    "symbol": "MANA",
    "thumb": "https://assets.coingecko.com/coins/images/878/thumb/decentraland-mana.png"
}, {
    "name": "Ontology",
    "symbol": "ONT",
    "thumb": "https://assets.coingecko.com/coins/images/3447/thumb/ONT.png"
}, {
    "name": "Huobi BTC",
    "symbol": "HBTC",
    "thumb": "https://assets.coingecko.com/coins/images/12407/thumb/Unknown-5.png"
}, {
    "name": "Telcoin",
    "symbol": "TEL",
    "thumb": "https://assets.coingecko.com/coins/images/1899/thumb/tel.png"
}, {
    "name": "UMA",
    "symbol": "UMA",
    "thumb": "https://assets.coingecko.com/coins/images/10951/thumb/UMA.png"
}, {
    "name": "Pirate Chain",
    "symbol": "ARRR",
    "thumb": "https://assets.coingecko.com/coins/images/6905/thumb/Pirate_Chain.png"
}, {
    "name": "Ravencoin",
    "symbol": "RVN",
    "thumb": "https://assets.coingecko.com/coins/images/3412/thumb/ravencoin.png"
}, {
    "name": "Liquity USD",
    "symbol": "LUSD",
    "thumb": "https://assets.coingecko.com/coins/images/14666/thumb/Group_3.png"
}, {
    "name": "0x",
    "symbol": "ZRX",
    "thumb": "https://assets.coingecko.com/coins/images/863/thumb/0x.png"
}, {
    "name": "Bancor Network Token",
    "symbol": "BNT",
    "thumb": "https://assets.coingecko.com/coins/images/736/thumb/bancor.png"
}, {
    "name": "ICON",
    "symbol": "ICX",
    "thumb": "https://assets.coingecko.com/coins/images/1060/thumb/icon-icx-logo.png"
}, {
    "name": "Helium",
    "symbol": "HNT",
    "thumb": "https://assets.coingecko.com/coins/images/4284/thumb/Helium_HNT.png"
}, {
    "name": "OMG Network",
    "symbol": "OMG",
    "thumb": "https://assets.coingecko.com/coins/images/776/thumb/OMG_Network.jpg"
}, {
    "name": "IOST",
    "symbol": "IOST",
    "thumb": "https://assets.coingecko.com/coins/images/2523/thumb/IOST.png"
}, {
    "name": "SwissBorg",
    "symbol": "CHSB",
    "thumb": "https://assets.coingecko.com/coins/images/2117/thumb/YJUrRy7r_400x400.png"
}, {
    "name": "Flow",
    "symbol": "FLOW",
    "thumb": "https://assets.coingecko.com/coins/images/13446/thumb/flow_logo.jpg"
}, {
    "name": "Horizen",
    "symbol": "ZEN",
    "thumb": "https://assets.coingecko.com/coins/images/691/thumb/horizen.png"
}, {
    "name": "Nano",
    "symbol": "NANO",
    "thumb": "https://assets.coingecko.com/coins/images/756/thumb/nano-coin-logo.png"
}, {
    "name": "Harmony",
    "symbol": "ONE",
    "thumb": "https://assets.coingecko.com/coins/images/4344/thumb/Y88JAze.png"
}, {
    "name": "Paxos Standard",
    "symbol": "PAX",
    "thumb": "https://assets.coingecko.com/coins/images/6013/thumb/paxos_standard.png"
}, {
    "name": "Venus",
    "symbol": "XVS",
    "thumb": "https://assets.coingecko.com/coins/images/12677/thumb/venus.png"
}, {
    "name": "Arweave",
    "symbol": "AR",
    "thumb": "https://assets.coingecko.com/coins/images/4343/thumb/oRt6SiEN_400x400.jpg"
}, {
    "name": "KuCoin Token",
    "symbol": "KCS",
    "thumb": "https://assets.coingecko.com/coins/images/1047/thumb/sa9z79.png"
}];