export const tooltipTexts: {
  [key: string]: string | { [key: string]: string }
} = {
  "table-project": "Name of the project.",
  "table-price": "Price of the token.",
  "table-price_24h": "Price change in the past 24h.",
  "table-price_7d": "Price change in the past 7 days.",
  "table-market_cap":
    "Market cap / valuation based on circulating supply of tokens.",
  "table-market_cap_fully_diluted":
    "Market cap / valuation based on the max. supply of tokens.",
  "table-volume_24h": "Trading volume of token in the past 24h.",
  "table-tvl":
    "Total value locked. Shows how much money is currently deposited into a project’s smart contracts.",
  "table-tvl_7d": "TVL change in the past 7 days.",
  "table-ps":
    "Price to sales (P/S) ratio. Calculated by dividing the fully-diluted market cap with the annualized revenue. Shows how a project is valued in relation to its revenues.",
  "chart-key-metrics":
    "Toggle between different key metrics and choose a time window.",
  "chart-revenue-share":
    "How is the total revenue (fees paid) divided between the supply-side participants and the tokenholders?",
  "chart-composition":
    "Which assets contribute most to the chosen metric. For example, which pool generates most trading fees.",
  "chart-competitive":
    "Choose a metric and compare the performance between two or more projects.",
  "chart-data-table": "Access the data in table format.",
  "chart-7d": "Show past week.",
  "chart-30d": "Show past month.",
  "chart-90d": "Show past quarter.",
  "chart-180d": "Show past six months.",
  "chart-max": "Show since launch.",
  "chart-latest": "Show latest.",
  "chart-expand": "Expand the chart for a screenshot.",
  "chart-copy-link": "Copy a shareable link to the chart.",
  "table-download-allowed": "Download table in CSV.",
  "chart-download-allowed": "Download chart in CSV.",
  "chart-total-revenue": "Total fees generated by the protocol.",
  "chart-historical-total-revenue": "Total fees generated by the protocol.",
  "chart-protocol-revenue": "Fees generated for the tokenholders.",
  "chart-historical-protocol-revenue": "Fees generated for the tokenholders.",
  "chart-ps":
    "Calculated by dividing the fully-diluted market cap with the annualized revenue. Shows how a project is valued in relation to its revenues.",
  "chart-metric-competitive": "Compare metrics with 2 or more projects.",
  "chart-tvl": "Total value of funds locked in the project’s smart contracts.",
  "chart-market-metrics":
    "Toggle between different market metrics and choose the time window.",
  "sidebar-home": "Go to home page.",
  "sidebar-markets": "Explore projects based on market segments.",
  "sidebar-metrics": "Explore projects based on metrics.",
  "sidebar-projects": "Explore blockchains and dapps.",
  "sidebar-insights": "Read and subscribe to our newsletter.",
  "sidebar-about": "Read more about our thesis, methodology and metrics.",
  "project-ath":
    "All time high. The highest price that the token has traded at.",
  "project-atl": "All time low. The lowest price that the token has traded at.",
  "project-markets": "Exchanges where the token can be traded.",
  "project-marketcap":
    "Market cap / valuation based on circulating supply of tokens.",
  "project-fully-diluted":
    "Market cap / valuation based on the max. supply of tokens.",
  "project-trading-vol-30d": "Trading volume in the past 30 days.",
  "project-annualized-transaction-vol":
    "Transaction volume on an annualized basis. Calculated based on past 30D average.",
  "project-revenue-7d": "Total fees paid in the past 7 days.",
  "project-revenue-30d": "Total fees paid in the past 30 days.",
  "project-revenue-annualized":
    "Total fees paid on an annualized basis. Calculated based on past 30D average.",
  "project-tvl":
    "Total value locked. Shows how much money is currently deposited into a project’s smart contracts.",
  "project-ps":
    "Price to sales (P/S) ratio. Calculated by dividing the fully-diluted market cap with the annualized revenue. Shows how a project is valued in relation to its revenues.",
  "project-treasury":
    "The value of tokens held in the treasury. The treasury can be used to fund protocol development, community grants, etc.",
  "project-exchanges":
    "On what exchanges is the token listed/where can the token be traded?",
  "keymetrics-market-cap":
    "Choose between fully-diluted or circulating market capitalization.",
  "keymetrics-gmv": "The part of TVL that is used to generate revenue.",
  "keymetrics-tvl": "Value of funds locked in the project's smart contracts.",
  "keymetrics-revenue":
    "Choose between total, supply-side, or protocol revenue.",
  "keymetrics-ps":
    "Fully-diluted market cap divided by annualized total revenue.",
  "keymetrics-volume": "Trading volume for the project's own token.",
  "revenue-supplyside":
    "Shows how much of total revenue goes to the supply-side.",
  "revenue-protocol":
    "Shows how much of total revenue goes to the tokenholders.",
  "composition-tvl": "TVL per asset.",
  "composition-revenue": "Revenue per asset.",
  "composition-gmv": "Volume per asset.",
  "competitive-metric": "Choose a metric you want to compare projects on.",
  "competitive-add-project": "Add a new project to the comparison.",
  "markets-revenue": "Total revenue generated by listed protocols.",
  "markets-tvl": "Value of funds locked in the project's smart contracts.",
  "markets-gmv": "Trading volume on listed exchanges.",
  "markets-market-cap":
    "Market cap / valuation based on circulating supply of tokens.",
  "markets-ps": "Fully-diluted market cap divided by annualized total revenue.",
  "markets-total-revenue": "",
  "markets-total-ps": "",
  "markets-median-revenue": "",
  "markets-dominance": "The leading dapp’s share of total exchange revenue.",
  "markets-title": "",
  "ps-dapps": "P/S ratio across popular decentralized applications.",
  "ps-blockchains": "P/S ratio across popular blockchains.",
  "tvl-dapps": "Total value locked across popular decentralized applications.",
  "metrics-title": "",
  "protocol-revenue-defi":
    "Protocol revenue across popular decentralized applications.",
  "protocol-revenue-blockchain": "Protocol revenue across popular blockchains.",
  "table-ps_24h_change": "P/S change in the past 24 hours.",
  "table-ps_7d_change": "P/S change in the past 7 days.",
  "table-ps_30d_change": "P/S change in the past 30 days.",
  "table-ps_180d_change": "P/S change in the past 180 days.",
  table_revenue_annualized:
    "Total revenue on an annualized basis. Calculated based on past 30D average.",
  table_revenue_24h: "Daily revenue. Total fees paid in the past 24 hours.",
  "table-revenue_7d": "Weekly revenue. Total fees paid in the past 7 days.",
  "table-revenue_30d": "Monthly revenue. Total fees paid in the past 30 days.",
  table_revenue_180d:
    "Semi-annual revenue. Total fees paid in the past 180 days.",
  "table-revenue_24h_change": "Revenue change in the past 24 hours.",
  "table-revenue_7d_change": "Revenue change in the past 7 days.",
  "table-revenue_30d_change": "Revenue change in the past 30 days.",
  "table-revenue_180d_change": "Revenue change in the past 180 days.",
  "table-revenue-protocol_24h":
    "Daily protocol revenue. Total fees paid to tokenholders in the past 24 hours.",
  "table-revenue-protocol_7d":
    "Weekly protocol revenue. Total fees paid to tokenholders in the past 7 days.",
  "table-revenue-protocol_30d":
    "Monthly protocol revenue. Total fees paid to tokenholders in the past 30 days.",
  "table-revenue-protocol_180d":
    "Semi-annual protocol revenue. Total fees paid to tokenholders in the past 180 days.",
  "table-revenue-protocol_24h_change":
    "Protocol revenue change in the past 24 hours.",
  "table-revenue-protocol_7d_change":
    "Protocol revenue change in the past 7 days.",
  "table-revenue_protocol_30d_change":
    "Protocol revenue change in the past 30 days.",
  "table-revenue_protocol_180d_change":
    "Protocol revenue change in the past 180 days.",
  table_gmv: "",
  "projects-table-title": "Data about projects listed on Token Terminal.",
  "markets-table-title": "Data about listed projects in current category.",
  "metrics-table-title": "Data about listed projects.",
  "total-revenue-dapps":
    "Total revenue across popular decentralized applications.",
  "total-revenue-blockchains": "Total revenue across popular blockchains.",
  "protocol-revenue-dapps":
    "Protocol revenue across popular decentralized applications.",
  "protocol-revenue-blockchains":
    "Protocol revenue across popular blockchains.",
  "metrics-total-tvl-defi":
    "Total value locked in listed decentralized applications.",
  "metrics-tvl-dominance":
    "The leading decentralized application's share of total TVL.",
  "metrics-tvl-highest":
    "Highest total value locked out of listed decentralized applications.",
  "metrics-tvl-lowest":
    "Lowest total value locked out of listed decentralized applications.",
  "metrics-highest-ps-defi": "Highest P/S ratio out of listed blockchains.",
  "metrics-lowest-ps-defi":
    "Lowest P/S ratio out of listed decentralized applications.",
  "metrics-highest-ps-blockchain":
    "Highest P/S ratio out of listed blockchains.",
  "metrics-lowest-ps-blockchain": "Lowest P/S ratio out of listed blockchains.",
  "metrics-protocol-revenue-defi":
    "Total fees generated for the tokenholders in listed decentralized applications.",
  "metrics-protocol-revenue-blockchain":
    "Total fees generated for the tokenholders in listed blockchains.",
  "metrics-protocol-revenue-dominance-defi":
    "The leading decentralized application's share of total protocol revenue.",
  "metrics-protocol-revenue-dominance-blockchain":
    "The leading blockchain's share of total protocol revenue.",
  "metrics-total-revenue-defi":
    "Total revenue generated in listed decentralized applications.",
  "metrics-total-revenue-blockchain":
    "Total revenue generated for the tokenholders in listed blockchains.",
  "metrics-revenue-dominance-defi":
    "The leading decentralized application's share of total revenue.",
  "metrics-revenue-dominance-blockchain":
    "The leading blockchain's share of total revenue.",
  "table-tvl_24h_change": "TVL change in the past 24 hours.",
  "table-tvl_7d_change": "TVL change in the past 7 days.",
  "table-tvl_30d_change": "TVL change in the past 30 days.",
  "table-tvl_180d_change": "TVL change in the past 180 days.",
  "table-tvl_30d":
    "TVL calculated based on past 30D average of listed projects.",

  exchange: {
    "markets-title": "Explore decentralized exchange protocols.",
    "table-gmv": "Trading volume on underlying exchange.",
    "markets-total-revenue":
      "Total trading fees generated by listed exchanges.",
    "markets-total-ps": "Median P/S ratio of listed exchanges.",
    "markets-median-revenue":
      "Median of total trading fees generated by listed exchanges.",
    "markets-dominance": "The leading exchange’s share of total trading fees.",
  },
  lending: {
    "markets-title": "Explore decentralized lending protocols.",
    "table-gmv": "Total borrow volume on underlying lending protocols.",
    "markets-total-revenue":
      "Total borrow interest generated on listed lending protocols.",
    "markets-total-ps": "Median P/S ratio of listed lending protocols.",
    "markets-median-revenue":
      "Median of total borrow interest generated by listed lending protocols.",
    "markets-gmv": "Borrow volume on listed lending protocols.",
    "markets-dominance":
      "The leading lending protocol’s share of total borrow interest.",
  },
  blockchain: {
    "markets-title": "Explore blockchains.",
    "table-gmv": "Total transaction volume on underlying blockchains.",
    "markets-total-revenue":
      "Total transaction fees generated on listed blockchains.",
    "markets-total-ps": "Median P/S ratio of listed blockchains.",
    "markets-median-revenue":
      "Median of total transaction fees generated by listed blockchains.",
    "markets-gmv": "Transaction volume on listed blockchains.",
    "markets-dominance":
      "The leading blockchains’s share of total transaction fees.",
  },
  defi: {
    "markets-title": "Explore decentralized finance protocols.",
    "table-gmv": "Total volume on underlying DeFi protocols.",
    "markets-total-revenue":
      "Total revenue generated on listed DeFi protocols.",
    "markets-total-ps": "Median P/S ratio of listed DeFi protocols.",
    "markets-median-revenue":
      "Median of total revenue generated by listed DeFi protocols.",
    "markets-gmv": "Transaction volume on listed DeFi protocols.",
    "markets-dominance":
      "The leading DeFi protocol’s share of total transaction fees.",
  },
  ps: {
    "metrics-title":
      "Calculated by dividing the fully-diluted market cap with the annualized revenue. Shows how a project is valued in relation to its revenues.",
  },
  revenue: {
    "metrics-title": "Total fees generated by the protocol.",
  },
  protocolRevenue: {
    "metrics-title": "Fees generated for the tokenholders.",
  },
  tvl: {
    "metrics-title": "Total value locked in smart contracts.",
  },
  uniswap: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Uniswap on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "saddle-finance": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Saddle on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "integral-protocol": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Integral on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "swerve-finance": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Swerve on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  pangolin: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Pangolin on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  piedao: {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on PieDAO on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per index.",
  },
  powerpool: {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on Powerpool on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per index.",
  },
  aave: {
    "project-revenue-7d":
      "Total interest & trading fees paid in the past 7 days.",
    "project-revenue-30d":
      "Total interest & trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest & trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on Aave on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  "0x": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on 0x on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "88mph": {
    "project-revenue-7d": "Total interest paid in the past 7 days.",
    "project-revenue-30d": "Total interest paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on 88mph on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  balancer: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Balancer on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  bancor: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Balancer on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  curve: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Curve on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "ellipsis-finance": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Ellipsis on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  dodo: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on DODO on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  dydx: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on dYdX on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  futureswap: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Futureswap on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  idex: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on IDEX on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  kyber: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Kyber on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  loopring: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Loopring on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "indexed-finance": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on Indexed Finance on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per index.",
  },
  mstable: {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total  return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on mStable on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  "perpetual-protocol": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Perpetual Protocol on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  polymarket: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Polymarket on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per category.",
    "keymetrics-gmv": "The trading volume on the Polymarket.",
  },
  sushiswap: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Sushiswap on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  synthetix: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Synthetix on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  tokenlon: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Tokenlon on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "binance-chain": {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Transaction volume on Binance Chain on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  bitcoin: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume Bitcoin on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  ethereum: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Ethereum on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  decred: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Decred on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  dogecoin: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Dogecoin on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  filecoin: {
    "project-revenue-7d":
      "Total transaction & storage fees paid in the past 7 days.",
    "project-revenue-30d":
      "Total transaction & storage fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction & storage fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Filecoin on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  kusama: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Kusama on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  polkadot: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Polkadot on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  litecoin: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Litecoin on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  rarible: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Rarible on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the protocol.",
  },
  stellar: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Stellar on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  terra: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Terra on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  tezos: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Tezos on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  zcash: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on zCash on an annualized basis. Calculated based on past 30D average.",
    "keymetrics-gmv": "The transaction volume on the blockchain.",
  },
  thorchain: {
    "project-revenue-7d": "Total transaction fees paid in the past 7 days.",
    "project-revenue-30d": "Total transaction fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transaction fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Thorchain on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Transaction volume per asset.",
    "keymetrics-gmv": "The Transaction volume on the blockchain.",
  },
  compound: {
    "project-revenue-7d": "Total interest paid in the past 7 days.",
    "project-revenue-30d": "Total interest paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on Compound on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  centrifuge: {
    "project-revenue-7d": "Total interest paid in the past 7 days.",
    "project-revenue-30d": "Total interest paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on Tinlake on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  cream: {
    "project-revenue-7d": "Total interest paid in the past 7 days.",
    "project-revenue-30d": "Total interest paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on Cream on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  makerdao: {
    "project-revenue-7d":
      "Total interest, trading & liquidation fees paid in the past 7 days.",
    "project-revenue-30d":
      "Total interest, trading & liquidation fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest, trading & liquidation fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on MakerDAO on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per collateral asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  reflexer: {
    "project-revenue-7d": "Total interest paid in the past 7 days.",
    "project-revenue-30d": "Total interest paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on Reflexer on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per collateral asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  "unit-protocol": {
    "project-revenue-7d": "Total interest paid in the past 7 days.",
    "project-revenue-30d": "Total interest paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on Unit on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per collateral asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  venus: {
    "project-revenue-7d": "Total interest paid in the past 7 days.",
    "project-revenue-30d": "Total interest paid in the past 30 days.",
    "project-revenue-annualized":
      "Total interest paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on Venus on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per collateral asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  "yearn-finance": {
    "project-revenue-7d": "Total return on investment in the past 7 days.",
    "project-revenue-30d": "Total return on investment in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investmentn on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on yearn on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  "vesper-finance": {
    "project-revenue-7d": "Total return on investment in the past 7 days.",
    "project-revenue-30d": "Total return on investment in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investmentn on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on yearn on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  hegic: {
    "project-revenue-7d":
      "Total premium & settlement fees paid in the past 7 days.",
    "project-revenue-30d":
      "Total premium & settlement fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total premium & settlement fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total notional transaction volume on Hegic on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "The notional transaction volume per asset.",
    "keymetrics-gmv": "The notional transaction volume on the exchange.",
  },
  keeperdao: {
    "project-revenue-7d": "Total return on investment in the past 7 days.",
    "project-revenue-30d": "Total return on investment in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total flash loan volume on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  livepeer: {
    "project-revenue-7d": "Total transcoding fees paid in the past 7 days.",
    "project-revenue-30d": "Total transcoding fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total transcoding fees paid on an annualized basis. Calculated based on past 30D average.",
  },
  metamask: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Metamask on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "mirror-protocol": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Mirror Protocol on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "nexus-mutual": {
    "project-revenue-7d": "Total insurance fees paid in the past 7 days.",
    "project-revenue-30d": "Total insurance fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total insurance fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total cover purchased on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Transaction volume per asset.",
    "keymetrics-gmv": "The transaction volume on the exchange.",
  },
  pancakeswap: {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on PancakeSwap on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  pooltogether: {
    "project-revenue-7d": "Total return on investment in the past 7 days.",
    "project-revenue-30d": "Total return on investment in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on Pooltogether volume on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  ren: {
    "project-revenue-7d": "Total burn & mint fees paid in the past 7 days.",
    "project-revenue-30d": "Total burn & mint fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total burn & mint fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Ren on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Total transaction volume per asset.",
    "keymetrics-gmv": "The transaction volume on the protocol.",
  },
  "keep-network": {
    "project-revenue-7d": "Total deposit fees paid in the past 7 days.",
    "project-revenue-30d": "Total deposit fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total deposit fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Keep Network on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Total transaction volume per asset.",
    "keymetrics-gmv": "The transaction volume on the protocol.",
  },
  uma: {
    "project-annualized-transaction-vol":
      "Transaction volume on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Total transaction volume per asset.",
  },
  "alchemix-finance": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  autofarm: {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  "enzyme-finance": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per vault.",
  },
  "fei-protocol": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  "harvest-finance": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  barnbridge: {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per market.",
  },
  "idle-finance": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  "lido-finance": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per asset.",
  },
  "index-cooperative": {
    "project-revenue-7d": "Total streaming fees paid in the past 7 days.",
    "project-revenue-30d": "Total streaming fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total streaming fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per index.",
    "composition-revenue": "Total streaming fees paid.",
  },
  "basket-dao": {
    "project-revenue-7d": "Total yield earned paid in the past 7 days.",
    "project-revenue-30d": "Total yield earned paid in the past 30 days.",
    "project-revenue-annualized":
      "Total yield earned  paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per index.",
  },
  instadapp: {
    "project-revenue-7d": "Total strategy fees paid in the past 7 days.",
    "project-revenue-30d": "Total strategy fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total strategy fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total transaction volume on Instadapp on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Total transaction volume per strategy.",
    "keymetrics-gmv": "The transaction volume on the protocol.",
  },
  liquity: {
    "project-revenue-7d":
      "Total withdrawal & redemption fees paid in the past 7 days.",
    "project-revenue-30d":
      "Total withdrawal & redemption fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total withdrawal & redemption fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total borrow volume on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Borrow volume per collateral asset.",
    "keymetrics-gmv": "The borrow volume on the protocol.",
  },
  "notional-finance": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on Pangolin on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per market.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "rari-capital": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per pool.",
  },
  "siren-markets": {
    "project-revenue-7d": "Total trading fees paid in the past 7 days.",
    "project-revenue-30d": "Total trading fees paid in the past 30 days.",
    "project-revenue-annualized":
      "Total trading fees paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total trading volume on SIREN on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Trading volume per asset.",
    "keymetrics-gmv": "The trading volume on the exchange.",
  },
  "stake-dao": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per pool.",
  },
  "set-protocol": {
    "project-revenue-7d": "Total return on investment paid in the past 7 days.",
    "project-revenue-30d":
      "Total return on investment paid in the past 30 days.",
    "project-revenue-annualized":
      "Total return on investment paid on an annualized basis. Calculated based on past 30D average.",
    "project-annualized-transaction-vol":
      "Total capital deployed on an annualized basis. Calculated based on past 30D average.",
    "composition-gmv": "Capital deployed per set.",
  },
}
